# encoding: ascii-8bit

# Copyright 2022 Ball Aerospace & Technologies Corp.
# All Rights Reserved.
#
# This program is free software; you can modify and/or redistribute it
# under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation; version 3 with
# attribution addendums as found in the LICENSE.txt
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# Modified by OpenC3, Inc.
# All changes Copyright 2025, OpenC3, Inc.
# All Rights Reserved
#
# This file may also be used under the terms of a commercial license
# if purchased from OpenC3, Inc.

services:
  openc3-minio:
    user: "${OPENC3_USER_ID:-1001}:${OPENC3_GROUP_ID:-1001}"
    image: "${OPENC3_REGISTRY}/${OPENC3_NAMESPACE}/openc3-minio${OPENC3_IMAGE_SUFFIX}:${OPENC3_TAG}"
    # Uncomment to run unit tests against the minio server
    # ports:
    #   - "127.0.0.1:9000:9000"
    volumes:
      - "openc3-bucket-v:/data"
      - "./cacert.pem:/devel/cacert.pem:z"
    command: server --address ":9000" --console-address ":9001" /data
    restart: "unless-stopped"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      MINIO_ROOT_USER: "${OPENC3_BUCKET_USERNAME}"
      MINIO_ROOT_PASSWORD: "${OPENC3_BUCKET_PASSWORD}"
      # Domain doesn't really matter but it's required. We really want the /minio path.
      # This is handled by our traefik configuration via rule: PathPrefix(`/minio`)
      # and forwarded on to the console at http://openc3-minio:9001
      MINIO_BROWSER_REDIRECT_URL: "http://openc3.com/minio"
      SSL_CERT_FILE: "/devel/cacert.pem"
      CURL_CA_BUNDLE: "/devel/cacert.pem"
      REQUESTS_CA_BUNDLE: "/devel/cacert.pem"
      NODE_EXTRA_CA_CERTS: "/devel/cacert.pem"

  # Uncomment to use QuestDB as the time series database
  # Also uncomment the openc3-tsdb-v volume in the volumes section
  # Also uncomment the OPENC3_TSDB_XXX env vars in the .env file
  # openc3-tsdb:
  #   image: "${OPENC3_REGISTRY}/${OPENC3_NAMESPACE}/openc3-tsdb${OPENC3_IMAGE_SUFFIX}:${OPENC3_TAG}"
  #   ports:
  #     # You should disable the QuestDB Console in production
  #     # as it gives unlimited access to the database
  #     - "127.0.0.1:9000:9000" # OPENC3_TSDB_INGEST_PORT & QuestDB Console
  #     # The Postgresql port doesn't typically need to be exposed to the host
  #     # but if you have external software that needs to connect to QuestDB
  #     # you can uncomment the following line to expose it.
  #     # - "127.0.0.1:8812:8812" # OPENC3_TSDB_QUERY_PORT
  #   volumes:
  #     - "openc3-tsdb-v:/var/lib/questdb"
  #   restart: "unless-stopped"
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"
  #   environment:
  #     QDB_PG_USER: "${OPENC3_TSDB_USERNAME}"
  #     QDB_PG_PASSWORD: "${OPENC3_TSDB_PASSWORD}"
  #     QDB_HTTP_USER: "${OPENC3_TSDB_USERNAME}"
  #     QDB_HTTP_PASSWORD: "${OPENC3_TSDB_PASSWORD}"

  openc3-redis:
    user: "${OPENC3_USER_ID:-1001}:${OPENC3_GROUP_ID:-1001}"
    image: "${OPENC3_REGISTRY}/${OPENC3_NAMESPACE}/openc3-redis${OPENC3_IMAGE_SUFFIX}:${OPENC3_TAG}"
    volumes:
      - "openc3-redis-v:${OPENC3_REDIS_VOLUME:-/data}"
      - "./cacert.pem:/devel/cacert.pem:z"
      - "./openc3-redis/users.acl:/config/users.acl:z"
    restart: "unless-stopped"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      SSL_CERT_FILE: "/devel/cacert.pem"
      CURL_CA_BUNDLE: "/devel/cacert.pem"
      REQUESTS_CA_BUNDLE: "/devel/cacert.pem"
      NODE_EXTRA_CA_CERTS: "/devel/cacert.pem"

  openc3-redis-ephemeral:
    user: "${OPENC3_USER_ID:-1001}:${OPENC3_GROUP_ID:-1001}"
    image: "${OPENC3_REGISTRY}/${OPENC3_NAMESPACE}/openc3-redis${OPENC3_IMAGE_SUFFIX}:${OPENC3_TAG}"
    volumes:
      - "openc3-redis-ephemeral-v:${OPENC3_REDIS_VOLUME:-/data}"
      - "./cacert.pem:/devel/cacert.pem:z"
      - "./openc3-redis/users.acl:/config/users.acl:z"
    restart: "unless-stopped"
    command: ["redis-server", "/config/redis_ephemeral.conf"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      SSL_CERT_FILE: "/devel/cacert.pem"
      CURL_CA_BUNDLE: "/devel/cacert.pem"
      REQUESTS_CA_BUNDLE: "/devel/cacert.pem"
      NODE_EXTRA_CA_CERTS: "/devel/cacert.pem"

  openc3-cosmos-cmd-tlm-api:
    user: "${OPENC3_USER_ID:-1001}:${OPENC3_GROUP_ID:-1001}"
    image: "${OPENC3_REGISTRY}/${OPENC3_NAMESPACE}/openc3-cosmos-cmd-tlm-api${OPENC3_IMAGE_SUFFIX}:${OPENC3_TAG}"
    restart: "unless-stopped"
    depends_on:
      - "openc3-redis"
      - "openc3-redis-ephemeral"
      - "openc3-minio"
    volumes:
      - "openc3-gems-v:/gems"
      - "./plugins:/plugins:z"
      - "./cacert.pem:/devel/cacert.pem:z"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      RAILS_ENV: "production"
      GEM_HOME: "/gems"
      PYTHONUSERBASE: "/gems/python_packages"
      OPENC3_REDIS_USERNAME: "${OPENC3_REDIS_USERNAME}"
      OPENC3_REDIS_PASSWORD: "${OPENC3_REDIS_PASSWORD}"
      OPENC3_BUCKET_USERNAME: "${OPENC3_BUCKET_USERNAME}"
      OPENC3_BUCKET_PASSWORD: "${OPENC3_BUCKET_PASSWORD}"
      OPENC3_SERVICE_PASSWORD: "${OPENC3_SERVICE_PASSWORD}"
      ANYCABLE_REDIS_URL: "redis://${OPENC3_REDIS_USERNAME}:${OPENC3_REDIS_PASSWORD}@${OPENC3_REDIS_HOSTNAME}:${OPENC3_REDIS_PORT}"
    env_file:
      - .env
    extra_hosts:
      - host.docker.internal:host-gateway

  openc3-cosmos-script-runner-api:
    user: "${OPENC3_USER_ID:-1001}:${OPENC3_GROUP_ID:-1001}"
    image: "${OPENC3_REGISTRY}/${OPENC3_NAMESPACE}/openc3-cosmos-script-runner-api${OPENC3_IMAGE_SUFFIX}:${OPENC3_TAG}"
    restart: "unless-stopped"
    depends_on:
      - "openc3-redis"
      - "openc3-redis-ephemeral"
      - "openc3-minio"
    volumes:
      - "openc3-gems-v:/gems:ro"
      - "./plugins:/plugins:z"
      - "./cacert.pem:/devel/cacert.pem:z"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      RAILS_ENV: "production"
      GEM_HOME: "/gems"
      PYTHONUSERBASE: "/gems/python_packages"
      OPENC3_REDIS_USERNAME: "${OPENC3_REDIS_USERNAME}"
      OPENC3_REDIS_PASSWORD: "${OPENC3_REDIS_PASSWORD}"
      OPENC3_BUCKET_USERNAME: "${OPENC3_BUCKET_USERNAME}"
      OPENC3_BUCKET_PASSWORD: "${OPENC3_BUCKET_PASSWORD}"
      OPENC3_SR_REDIS_USERNAME: "${OPENC3_SR_REDIS_USERNAME}"
      OPENC3_SR_REDIS_PASSWORD: "${OPENC3_SR_REDIS_PASSWORD}"
      OPENC3_SR_BUCKET_USERNAME: "${OPENC3_SR_BUCKET_USERNAME}"
      OPENC3_SR_BUCKET_PASSWORD: "${OPENC3_SR_BUCKET_PASSWORD}"
      OPENC3_SERVICE_PASSWORD: "${OPENC3_SERVICE_PASSWORD}"
      ANYCABLE_REDIS_URL: "redis://${OPENC3_REDIS_USERNAME}:${OPENC3_REDIS_PASSWORD}@${OPENC3_REDIS_HOSTNAME}:${OPENC3_REDIS_PORT}"
    env_file:
      - .env

  openc3-operator:
    user: "${OPENC3_USER_ID:-1001}:${OPENC3_GROUP_ID:-1001}"
    image: "${OPENC3_REGISTRY}/${OPENC3_NAMESPACE}/openc3-operator${OPENC3_IMAGE_SUFFIX}:${OPENC3_TAG}"
    restart: "unless-stopped"
    # ports:
    #   - "127.0.0.1:7779:7779" # Open port for the demo router
    #   - "127.0.0.1:8081:8081/udp" # Open a udp port
    depends_on:
      - "openc3-redis"
      - "openc3-redis-ephemeral"
      - "openc3-minio"
    volumes:
      - "openc3-gems-v:/gems:ro"
      - "./plugins:/plugins:z"
      - "./cacert.pem:/devel/cacert.pem:z"
      # Add access to the entire C drive on Windows
      # - "/c:/c"
      # Create a dropbox and archive folder for ingest by FileInterface and PreidentifiedRouter
      # - /Users/jmthomas/dropbox:/dropbox
      # - /Users/jmthomas/archive:/archive
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      # CI in set in Github actions, changes the Demo TLM_LOG_CYCLE_TIME
      # By not setting a value it pases the environment variable from the shell
      # straight to the container and doesn't complain if CI is not set
      - CI
      - GEM_HOME=/gems
      - PYTHONUSERBASE=/gems/python_packages
      - OPENC3_REDIS_USERNAME=${OPENC3_REDIS_USERNAME}
      - OPENC3_REDIS_PASSWORD=${OPENC3_REDIS_PASSWORD}
      - OPENC3_BUCKET_USERNAME=${OPENC3_BUCKET_USERNAME}
      - OPENC3_BUCKET_PASSWORD=${OPENC3_BUCKET_PASSWORD}
      - OPENC3_SERVICE_PASSWORD=${OPENC3_SERVICE_PASSWORD}
    env_file:
      - .env
    extra_hosts:
      - host.docker.internal:host-gateway

  openc3-traefik:
    user: "${OPENC3_USER_ID:-1001}:${OPENC3_GROUP_ID:-1001}"
    image: "${OPENC3_REGISTRY}/${OPENC3_NAMESPACE}/openc3-traefik${OPENC3_IMAGE_SUFFIX}:${OPENC3_TAG}"
    volumes:
      - "./cacert.pem:/devel/cacert.pem:z"
      - "./openc3-traefik/traefik.yaml:/etc/traefik/traefik.yaml:z"
      # - "./openc3-traefik/traefik-allow-http.yaml:/etc/traefik/traefik.yaml:z"
      # - "./openc3-traefik/traefik-ssl.yaml:/etc/traefik/traefik.yaml:z"
      # - "./openc3-traefik/traefik-letsencrypt.yaml:/etc/traefik/traefik.yaml:z"
      # - "./openc3-traefik/cert.key:/etc/traefik/cert.key:z"
      # - "./openc3-traefik/cert.crt:/etc/traefik/cert.crt:z"
    ports:
      - "127.0.0.1:2900:2900"
      - "127.0.0.1:2943:2943"
      # - "80:2900"
      # - "443:2943"
    restart: "unless-stopped"
    depends_on:
      - "openc3-redis"
      - "openc3-redis-ephemeral"
      - "openc3-minio"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      SSL_CERT_FILE: "/devel/cacert.pem"
      CURL_CA_BUNDLE: "/devel/cacert.pem"
      REQUESTS_CA_BUNDLE: "/devel/cacert.pem"
      NODE_EXTRA_CA_CERTS: "/devel/cacert.pem"

  openc3-cosmos-init:
    user: "${OPENC3_USER_ID:-1001}:${OPENC3_GROUP_ID:-1001}"
    image: "${OPENC3_REGISTRY}/${OPENC3_NAMESPACE}/openc3-cosmos-init${OPENC3_IMAGE_SUFFIX}:${OPENC3_TAG}"
    restart: on-failure
    depends_on:
      - "openc3-traefik"
      - "openc3-redis"
      - "openc3-redis-ephemeral"
      - "openc3-minio"
    volumes:
      - "openc3-gems-v:/gems"
      - "./plugins:/plugins:z"
      - "./cacert.pem:/devel/cacert.pem:z"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      # CI in set in Github actions, changes the Demo TLM_LOG_CYCLE_TIME
      # By not setting a value it pases the environment variable from the shell
      # straight to the container and doesn't complain if CI is not set
      - CI
      - GEM_HOME=/gems
      - PYTHONUSERBASE=/gems/python_packages
      - OPENC3_REDIS_USERNAME=${OPENC3_REDIS_USERNAME}
      - OPENC3_REDIS_PASSWORD=${OPENC3_REDIS_PASSWORD}
      - OPENC3_BUCKET_USERNAME=${OPENC3_BUCKET_USERNAME}
      - OPENC3_BUCKET_PASSWORD=${OPENC3_BUCKET_PASSWORD}
      - OPENC3_SR_BUCKET_USERNAME=${OPENC3_SR_BUCKET_USERNAME}
      - OPENC3_SR_BUCKET_PASSWORD=${OPENC3_SR_BUCKET_PASSWORD}
    env_file:
      - .env

volumes:
  # openc3-tsdb-v: {}
  openc3-redis-v: {}
  openc3-redis-ephemeral-v: {}
  openc3-bucket-v: {}
  openc3-gems-v: {}
